development:
  adapter: postgresql
  encoding: utf8
  database: api
  pool: 5
  username: postgres
  password: 1234567

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: api
  pool: 5
  username: postgres
  password: 1234567  

production:
  adapter: postgresql
  encoding: utf8
  database: api
  pool: 5
  username: postgres
  password: 1234567
